labs/django/mysite/blog/urls.py
from django.urls import path
from . import views
from .views import BlogPostLike

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new',),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<pk>/delete', views.post_delete, name='post_delete'),
    path('blogpost-like/<int:pk>', views.BlogPostLike, name='blogpost_like')
    
    
    
]

labs/django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls'))
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labs/django/mysite/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_user, name='logout_user'),
    path('profile_page', views.profile_page, name='profile_page'),
]

labs/django/mysite/blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='blogpost_like')
    blog_picture = models.ImageField(upload_to='images/', null=True, blank=True)
    def number_of_likes(self):
        return self.likes.count()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_image(self):
        if self.blog_picture:
            return self.blog_picture.url
        return ''

labs/django/mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    profile_picture = models.ImageField(upload_to='images/', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='user_profile')


    def __str__(self):
        return self.user.username + ' - ' + str(self.profile_picture.name)

labs/django/mysite/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta: 
        model = Post
        fields = ('title', 'text', 'blog_picture')

labs/django/mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'image']

labs/django/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, reverse, redirect, Http404
from django.utils import timezone
from .models import Post
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    author = post.author 
    user = request.user
    return render(request, 'blog/post_detail.html', {'post': post,})

def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return HttpResponseRedirect(reverse('blog:post_list'))



def BlogPostLike(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    if post.likes.filter(id=request.user.id).exsists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    
    return HttpResponseRedirect(reverse('blog:post_list', args=[str(pk)]))






class BlogPostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        # context[""] = 
        likes_connected = get_object_or_404(Post, id=self.kwargs['pk'])
        liked = False
        if likes_connected.likes.filter(id=self.request.user.id).exists():
            liked = True
        data['number_of_likes'] = likes_connected.number_of_likes()
        data['post_is_liked'] = liked
        data['randomentry'] = 'everybody_loves_taco_bell'
        return data


@login_required
def BlogPostLike(request, pk):
    print(pk, 'line57')
    post = get_object_or_404(Post, id=pk)
    print(post,'line59')
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    return redirect('blog:post_detail', pk=post.pk)


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        raise Http404
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def home(request):
    return HttpResponseRedirect(reverse('blog:post_list'))

labs/django/mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.models import User
from blog.models import Post
from .models import UserProfile
import django.contrib.auth
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import logout
# Create your views here.


def logout_user(request):
    logout(request)
    return redirect('blog:post_list')



def register(request):
    # return HttpResponse('ok')

    if request.method == 'POST':
        form = UserRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            # create a user from the submitted form data
            user = form.save()
            # getting the image that was chosen by the user
            # profile_picture = request.FILES.get('image')
            profile_picture = form.cleaned_data['image']
            # creating a user profile associated with this user and image
            user_profile = UserProfile(user=user, profile_picture=profile_picture)
            user_profile.save()

            messages.success(request, f'Account created for {user.username}!')
            django.contrib.auth.login(request, user)
            return redirect('blog:post_list')
        else:
            return render(request, 'users/register.html', {'form': form})
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = django.contrib.auth.authenticate(request, username=username, password=password)
        if user is not None:
            django.contrib.auth.login(request, user)
            return redirect('blog:post_list')
        else:
            messages.info(request, 'Invalid username or password')
    return render(request, 'users/login.html', {})

def profile_page(request):
    posts = Post.objects.filter(author = request.user).order_by('-published_date')
    return render(request, 'blog/profile_page.html',{'posts': posts})

labs/django/mysite/blog/templates/blog/base.html
{% load static %}

<html>

<head>
    <title>New Blogs</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>


<body>
    

    <nav class="navbar fixed-top navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog:post_list' %}">Bloggers- <strong>{{ user.username}}</strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'blog:post_list' %}">Home page <i class="bi bi-house-fill"></i>
                    </a>
                    {% if user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'users:profile_page' %}">Your profile<i
                            class="bi bi-briefcase-fill"></i></a>
                    <a class="nav-link" href="{% url 'blog:post_new' %}">New Post <i class="bi bi-plus-square"></i></a>
                    <a href="{% url 'users:logout_user'%}">Logout <i class="bi bi-box-arrow-right"></i></a>
                    {% else %}
                    <a class="nav-link" href="{% url 'users:register' %}">Register <i
                            class="bi bi-person-plus-fill"></i></a>
                    <a class="nav-link" href="{% url 'users:login' %}">Sign in now <i
                            class="bi bi-door-open"></i></i></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <hr>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <div class="content container">
        <div class="row">
            <div class="col-sm">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
</body>

</html>

labs/django/mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <h2>{{ post.title }}</h2>
        <h3>Author-{{post.author}}</h3>
        
        {% if post.get_image %}
        <img src="{{post.get_image}}"/>
        {% endif %}
        <p>{{ post.text|linebreaksbr }}</p>
        <!--  -->
        
        {% if user.is_authenticated %}
        <form action="{% url 'blog:blogpost_like' pk=post.pk %}" method="POST">
          {% csrf_token %}
      
          {% if post_is_liked %}
          <button type="submit" name="blogpost_id" value="{{object.id}}" class="btn btn-info">Unlike</button>
          {% else %}
          <button type="submit" name="blogpost_id" value="{{object.id}}" class="btn btn-info">Like</button>
          {% endif %}
        </form>
      {% else %}
        <a class="btn btn-outline-info" href="{% url 'users:login' %}">Log in to like this article!</a><br>
      {% endif %}
      <strong class="text-secondary">{{ number_of_likes }} Like(s){{ number_of_likes|pluralize }}{{randomentry}}</strong>
<hr>
        <!--  -->
        <div>
        {% if user.is_authenticated and user == post.author %}
        <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}">Edit Post</a>
        <a class="btn btn-danger" href="{% url 'blog:post_delete' pk=post.pk %}">Delete post</a>
        {% endif %}
        </div>
    </div>

    <style>
    img{
        height: 200px;
    }
    </style>
{% endblock %}
{% comment %} 
make improvements to profile home page,
sections for code wars stuff
start blogging every day with coding details


{% endcomment %}

labs/django/mysite/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>New post</h2>
<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <hr>
    <button type="submit" class="save btn btn-success">Save</button>
</form>
{% endblock %}

labs/django/mysite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for post in posts %}
<div class="post">
    <div class="date">
        {{ post.published_date }}
    </div>
    <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
    <p class="author">author: {{post.author}}</p>
    <p>{{ post.text|linebreaksbr }}</p>

</div>
{% endfor %}
{% endblock %}

labs/django/mysite/blog/templates/blog/profile_page.html
{% extends 'blog/base.html' %}

{% block content%}
<div class="profile_home">
  <h1 class='username_home'> <small>Profile Home for </small><u>{{user.username}}</u></h1>
  <div class="profile_photo"><img src="{{user.user_profile.profile_picture.url}}" /></div>
</div>
{% for post in posts %}
<div class="post">
  <div class="date">
    {{ post.published_date }}
  </div>
  <h2><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
  <p class='blog_body'>{{ post.text|linebreaksbr }}</p>
</div>
{% endfor %}








{% comment %} <div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
        aria-expanded="true" aria-controls="collapseOne">
        Accordion Item #1
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the first item's accordion body.</strong> It is hidden by default, until the collapse plugin
        adds the appropriate classes that we use to style each element. These classes control the overall appearance, as
        well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our
        default variables. It's also worth noting that just about any HTML can go within the
        <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo"
        aria-expanded="false" aria-controls="collapseTwo">
        Accordion Item #2
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin
        adds the appropriate classes that we use to style each element. These classes control the overall appearance, as
        well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our
        default variables. It's also worth noting that just about any HTML can go within the
        <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree"
        aria-expanded="false" aria-controls="collapseThree">
        Accordion Item #3
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
      data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin
        adds the appropriate classes that we use to style each element. These classes control the overall appearance, as
        well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our
        default variables. It's also worth noting that just about any HTML can go within the
        <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>
</div> {% endcomment %}
<style>
  img {
    height: 200px;
    margin-bottom: 10px;
  }
</style>
{% endblock %}

labs/django/mysite/users/templates/users/login.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content%}

<form action="" method="post">
{% csrf_token %}
  <div class="mb-3">
    <label for="username"  class="form-label">username</label>
    <input type="username" name="username" class="form-control" id="username1">
  </div>
  {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
  <div class="mb-3">
    <label for="password"  class="form-label">Password</label>
    <input type="password" name="password" class="form-control" id="Password1">
  </div>
  <button type="submit" class="btn btn-primary">Sign In</button>
</form>

{%endblock %}

labs/django/mysite/users/templates/users/register.html
{% extends "blog/base.html"%}
{% load crispy_forms_tags %}
{% block content%}
    <div class="content-section">
        <form action='{% url "users:register"%}' method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">join today</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">sign up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a href="{% url 'users:login' %}" class="ml-2"> Sign in</a>
            </small>
        </div>
    </div>
{%endblock content%}