labs/django/contact_list/contact_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contactapp.urls'))

]

labs/django/contact_list/contactapp/urls.py
from django.urls import path
from . import views

app_name = 'contactapp'
urlpatterns = [
    path('', views.index, name='index'),
    # localhost:8000/contactapp/detail/5/
    path('detail/<int:contact_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('savecontact/', views.save_contact, name='savecontact')
]

labs/django/contact_list/contactapp/models.py
from django.db import models

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=200)
    state = models.CharField(max_length=200)

    def __str__(self):
        return self.name + ', ' + self.state
    

class Contact(models.Model):
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20, blank=True)
    last_name = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    city = models.ForeignKey(City, on_delete=models.PROTECT, related_name='contacts')
    notes = models.CharField(max_length=300)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.first_name + ' ' + self.middle_name + ' ' + self.last_name + '-' + self.email
    

labs/django/contact_list/contactapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from .models import City, Contact


# Create your views here.

def index(request):
    contact_people = Contact.objects.order_by('last_name') 
    context = {
        'contact_people': contact_people,
    }
    
    return render(request, 'contactapp/index.html', context)

def detail(request, contact_id):
    contact = Contact.objects.get(id=contact_id)
    context = {
        'contact': contact,
    }
    return render(request, 'contactapp/detail.html', context)
    # return HttpResponse("You're looking at contact wtih id " + str(contact_id))

def create(request):
    cities = City.objects.all()
    context = {
        'cities': cities
    }
    return render(request,'contactapp/create.html', context)

def save_contact(request):
    print(request.POST)
    # extract form data into local variables
    first_name = request.POST['first_name']
    middle_name = request.POST['middle_name']
    last_name = request.POST['last_name']
    email = request.POST['email']
    phone_number = request.POST['phone_number']
    notes = request.POST['notes']
    city_id = request.POST['city_id']
    existing_city = City.objects.get(id=city_id)
    contact = Contact(first_name = first_name, middle_name=middle_name, last_name=last_name, email =email, phone_number = phone_number, notes = notes, city = existing_city  )
    # create instance of model using data
    contact.save()
    #save the model to the database 
    
    #redirect back to index page
    return HttpResponseRedirect(reverse('contactapp:index'))
    # return render(request, 'contactapp/index.html')
    # return HttpResponse(dict(test))

labs/django/contact_list/contactapp/templates/contactapp/base.html
{% comment %} {% load static %} {% endcomment %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

  <title>Contact App</title>
</head>

<body>
  
    {% block content %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>
</body>

</html>

labs/django/contact_list/contactapp/templates/contactapp/create.html
{% extends 'contactapp/base.html'%}

{% block content %}

<div class='container'>
    <div class="row">
        <form action="{% url 'contactapp:savecontact' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="first" class="form-label">First Name</label>
                <input type="text" name="first_name" class="form-control" id="first" aria-describedby="emailHelp">
            </div>
            <div class="mb-3">
                <label for="middle" class="form-label">Middle Name</label>
                <input type="text"name="middle_name" class="form-control" id="middle">
            </div>
            <div class="mb-3">
                <label for="last" class="form-label">Last Name</label>
                <input type="text" name="last_name" class="form-control" id="last">
            </div>

            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" name="email" class="form-control" id="email">
            </div>
            <div class="mb-3">
                <label for="phonenumber" class="form-label">Phone Number</label>
                <input type="tel" name="phone_number" class="form-control" id="phonenumber">
            </div>

            <div class="mb-3">
                <label for="city" class="form-label">City</label>
                <select name="city_id" class="form-select" id="">
                    <option selected disabled value="">Select a City</option>
                    {% for city in cities %}
                    <option value="{{ city.id }}">{{city.name}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="notes" class="form-label">Notes</label>
                <input type="text" name="notes" class="form-control" id="notes">
            </div>
            <div class='mb-3'>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>
{%endblock%}

labs/django/contact_list/contactapp/templates/contactapp/detail.html
{%extends 'contactapp/base.html'%}
    

{% block content %}
<h1>Detail Page</h1>
<hr>
    <table class="table table-striped">
      <tbody>
      <tr>
      <!-- <td>first name</td> -->
        <!-- <td>{{contact.id}}</td> -->
      </tr>
      <tr>
        <td> First Name :</td>
        <td>{{contact.first_name}}</td>
      </tr>
      <tr>
        <td>Middle Name :</td>
        <td>{{contact.middle_name}}</td>
      </tr>
      <tr>
        <td>Last Name : </td>
        <td>{{contact.last_name}}</td>
      </tr>  
      <tr>
        <td>Email :</td>
        <td>{{contact.email}}</td>
      </tr>
      <tr>
        <td>Notes</td>
        <td>{{contact.notes}}</td>
      </tr>
      <tr>
        <td><a href="{% url 'contactapp:index' %}"   class="btn btn-primary">Back</a>
      </tr>
  
    </tbody>
  </table>
    
{% endblock %}
    
    
    
    
    

labs/django/contact_list/contactapp/templates/contactapp/index.html
{% extends 'contactapp/base.html'%}

{% block content %}
  <h1>Contacts</h1>
  <table class="table table-striped">
    <thead>
      <tr>

        <th scope="col">First</th>
        <th scope="col">Middle</th>
        <th scope="col">Last</th>
        <th scope="col">Email</th>
        <th scope="col">Detail</th>
      </tr>
    </thead>
    <tbody>
      {% for contact in contact_people %}
      <tr>
        <td>{{contact.first_name}}</td>
        <td>{{contact.middle_name}}</td>
        <td>{{contact.last_name}}</td>
        <td>{{contact.email}}</td>
        <td><a href="{% url 'contactapp:detail' contact.id %}"   class="btn btn-primary">Details</a>
        </td>
        <!-- <td><button>button</button></td> -->
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'contactapp:create'%}" class="btn btn-primary">Add</a>
{% endblock %}