labs/django/ToDo_list/ToDo_app/urls.py
from django.urls import path
from . import views

app_name = 'ToDo_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('save_todo_item/', views.save_todo_item, name='save_todo_item' ),
    path('completed_todo/<int:text_id>', views.completed_todo, name='completed_todo'),
    path('delete_item/<int:completed_todo_id>', views.delete_item, name='delete_item'),
    path('delete_all/', views.delete_all, name='delete_all')
]

labs/django/ToDo_list/ToDo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDo_app.urls'))
]

labs/django/ToDo_list/ToDo_app/models.py
from django.db import models

# Create your models here.
class Priority(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    


class ToDoItem(models.Model):
    text = models.CharField(max_length=200)
    priority = models.ForeignKey(Priority, on_delete=models.PROTECT, related_name='Priority')
    created_date = models.DateTimeField()
    completed_date = models.DateTimeField(null=True, blank=True)
    completed = models.BooleanField(default=False)
    def __str__(self):
        return self.text
    

labs/django/ToDo_list/ToDo_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Priority, ToDoItem
from datetime import datetime
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.




def index(request):
    items = ToDoItem.objects.filter(completed=False).order_by('created_date')
    priorities = Priority.objects.all()
    completed_todos = ToDoItem.objects.filter(completed=True).order_by('created_date')
    # print(completed_todos)
    context = {
        'items': items,
        'priorities': priorities,
        'completed_todos': completed_todos,
    }
    return render(request, 'ToDo_app/index.html', context)

def save_todo_item(request):
    print(request.POST)
    priority_id = request.POST['priority_id']
    priorities = Priority.objects.get(id=priority_id)
    text = request.POST['text']
    # dueDate = request.POST[]
    created_date = timezone.now()
    to_do_item = ToDoItem(text = text, created_date = created_date, priority = priorities)
    to_do_item.save()

    return HttpResponseRedirect(reverse('ToDo_app:index'))

def delete_item(request, completed_todo_id):
    items_completed = ToDoItem.objects.get(id=completed_todo_id)
    # print(items_completed)
    items_completed.delete()

    return HttpResponseRedirect(reverse('ToDo_app:index'))



def completed_todo(request, text_id):
    item = ToDoItem.objects.get(id=text_id)
    item.completed = True
    item.save()
    # print(item)
    return HttpResponseRedirect(reverse('ToDo_app:index'))


def delete_all(request):
    # completed_items = completed_todo(request, text_id)
    completed_todos = ToDoItem.objects.filter(completed=True)
    completed_todos.delete()
    print(completed_todos)
    print('this is a marker')
    return HttpResponseRedirect(reverse('ToDo_app:index'))

labs/django/ToDo_list/ToDo_app/templates/ToDo_app/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- google fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'ToDo_app/main.css'%}">
  <title>To Do site</title>

</head>

<body>
  <div class="container-lg">
    <h1>To Do List</h1>
    <div id="contentboxes">
      <table class="table table-borderless table-hover">
        <thead>
          <tr>
            <th>Task</th>
            <th>Priority</th>
            <th>Completed?</th>
          </tr>
        </thead>
        <tbody>
          {% for item in items %}
          <tr>
            <td id="item-text">{{item.text}}</td>
            <td class="{{item.priority.name}}"><strong>{{item.priority.name}}</strong></td>
            <td><a href="{% url 'ToDo_app:completed_todo' item.id %}" class="btn btn-warning">Completed</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div id="contentboxes" class='mid-box'>
      <form action="{% url 'ToDo_app:save_todo_item'%}" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="text" class="form-label"><strong>Item Description</strong></label>
          <input type="text" placeholder='enter an item' name='text' class="form-control" id="item_text"
            aria-describedby="emailHelp">
          {% comment %} <input type="date" id="start" for="date" name="task-due" value="2020-01-01" min="2018-01-01" max="2022-12-31"> {% endcomment %}
        </div>


        <div class="mb-3" id='priority-level'>
          <label for="priorities" class="form-label"><strong>Priority level</strong> </label>
          <select name="priority_id" class="form-select" id="priorities">
            <option id="priority_text" selected disabled value="">Select a priority</option>
            {% for priority in priorities %}
            <option class="{{completed_todo.priority.name}}" value="{{priority.id}}">{{priority.name}}</option>
            {% endfor %}
          </select>
          <!-- <input type="text" name="Priority" class="form-control" id="Priority"> -->
          <div id='submit-btn'>
            <button type="submit" class="btn btn-primary btn-lg">Submit</button>
          </div>
        </div>
    </div>
    </form>
    <hr>

    <div class="mx-auto" id="completed-content">
      <h2>Completed Items</h2>
      <a href="{% url 'ToDo_app:delete_all' %}" class="btn btn-danger">Delete all</a>
    </div>
    <div id="contentboxes">
      <table class="table table-borderless table-hover ">
        <thead>
          <tr>
            <th>Task</th>
            <th>Date</th>
            <th>Priority</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for completed_todo in completed_todos %}
          <tr>
            <td>
              <p><s>{{completed_todo.text}}</s></p>
            </td>
            <td>{{completed_todo.created_date}}</td>
            <td class="{{completed_todo.priority.name}}">{{completed_todo.priority.name}}</td>
            <td><a href="{% url 'ToDo_app:delete_item' completed_todo.id %}" class="btn btn-danger">Delete?</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>



  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
    crossorigin="anonymous"></script>

</body>

</html>