labs/django/urlProject/urlApp/urls.py
from django.urls import path
from . import views


app_name = 'urlApp'
urlpatterns = [
    path('save_url', views.save_url, name='save_url'),
    path('<str:code>/', views.site_redirect, name='redirect'),
    path('delete/<int:save_url_id>/', views.delete_URL, name='delete_url'),
    path('', views.index, name='index'),
]

labs/django/urlProject/urlProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urlApp.urls'))
]

labs/django/urlProject/urlApp/models.py
from django.db import models

# Create your models here.
class ShortenedURL(models.Model):
    code = models.CharField(max_length=100)
    url = models.URLField(max_length=100)
    counter = models.IntegerField(default=0)

    def __str__(self):
        return self.url
    

labs/django/urlProject/urlApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import ShortenedURL
from django.urls import reverse
import random
import string


def random_string_creator():
    chars = list(string.ascii_letters + string.digits)
    y = 0
    x = 6
    out_lst = []
    while y < x:
        out_lst.append(random.choice(chars))
        y +=1
    url_code = "".join(out_lst)
    return url_code


# Create your views here.
def index(request):
    urls = ShortenedURL.objects.all()
    context = {
        'urls': urls,
        
    }
    return render(request, 'urlApp/index.html', context)

def delete_URL(request, save_url_id):
    completed_url = ShortenedURL.objects.get(id=save_url_id)
    completed_url.delete()

    return HttpResponseRedirect(reverse('urlApp:index'))

def save_url(request):
    long_url = request.POST['long_url']
    url_code = random_string_creator()
    code = url_code
    shortened_url = ShortenedURL(url = long_url, code = code)
    shortened_url.save()

    return HttpResponseRedirect(reverse('urlApp:index'))




def site_redirect(request, code):
    print(code)
    shortened_url = ShortenedURL.objects.get(code=code)
    shortened_url.counter += 1
    print(shortened_url)
    shortened_url.save()
    return redirect(shortened_url.url)
   

     
    

labs/django/urlProject/urlApp/templates/urlApp/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'urlApp/main.css'%}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>URL Shortener</title>
</head>

<body>






    <div class="container">
        <div class="row">
            <div class="col-sm-12" id="enter_area">
                <form action="{% url 'urlApp:save_url'%}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="long_url">
                            <h1>Tiny URL creator</h1>
                        </label>
                        <input type="text" name="long_url" required class="form-control" id="url_input"
                            aria-describedby="url_input" placeholder="Enter url">
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                    
                    <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="d-flex">
                            <div class="toast-body">
                                Short URL copied
                            </div>
                            <button type="button" class="btn-close me-1 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                    </div>
                
                
                </form>
            </div>
        </div>
    </div>

    <hr>

    <table id="table_urls" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th scope="col">Long URL</th>
                <th scope="col">Short URL</th>
                <th scope="col"> Copy</th>
                <th scope="col"># accessed</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for url in urls %}
            <tr>
                <td>{{ url.url }}</td>
                <td id="url_short">http://127.0.0.1:8000/{{url.code}}</td>
                <td>
                    <button type="button"
                        onclick="navigator.clipboard.writeText('http://127.0.0.1:8000/{{url.code}}') "
                        class="btn btn-outline-success btn-sm btn_copy">copy</button>
                </td>
                <td>{{url.counter}}</td>
                <td><a href="{% url 'urlApp:delete_url' url.id %}" id="deletebtn" type="button"
                        class="btn btn-outline-danger btn-sm">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% for url in urls %}
    <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: {{url.counter}}%" aria-valuenow="50" aria-valuemin="1" aria-valuemax="10">{{ url.url }}</div>
      </div>
      
    <hr>
    </div>
    {% endfor %}
    <hr>

    <!-- <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                Short URL copied
            </div>
            <button type="button" class="btn-close me-1 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div> -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
    <script>
        let toast = new bootstrap.Toast(document.querySelector('.toast'))
        console.log(toast)

        let liveToastBtns = document.querySelectorAll('.btn_copy')
        for (btn of liveToastBtns) {
            btn.addEventListener('click', function () {
                toast.show()
            })
        }

    </script>

    <script src="{% static 'urlApp/main.js'%}"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


</body>

</html>